/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as authenticationAccountSuccessRouteImport } from './routes/(authentication)/accountSuccess'
import { Route as authenticationAccountVerificationRouteImport } from './routes/(authentication)/accountVerification'
import { Route as authenticationForgotPasswordRouteImport } from './routes/(authentication)/forgotPassword'
import { Route as authenticationLoginRouteImport } from './routes/(authentication)/login'
import { Route as authenticationPasswordSuccessRouteImport } from './routes/(authentication)/passwordSuccess'
import { Route as authenticationRegisterRouteImport } from './routes/(authentication)/register'
import { Route as authenticationResetPasswordRouteImport } from './routes/(authentication)/resetPassword'
import { Route as authenticationUnexpectedIssueRouteImport } from './routes/(authentication)/unexpectedIssue'
import { Route as authenticationUnexpectedIssueVRouteImport } from './routes/(authentication)/unexpectedIssueV'
import { Route as authenticationVerificationCodeRouteImport } from './routes/(authentication)/verificationCode'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as dashboardDashboardCookRouteImport } from './routes/(dashboard)/dashboardCook'
import { Route as dashboardDashboardWaiterRouteImport } from './routes/(dashboard)/dashboardWaiter'
import { Route as menuAdminCustomDishFormRouteImport } from './routes/(menuAdmin)/customDishForm'
import { Route as menuAdminEditMenuRouteImport } from './routes/(menuAdmin)/editMenu'
import { Route as menuAdminMenuManagmentRouteImport } from './routes/(menuAdmin)/menuManagment'
import { Route as menuAdminSimpleDishFormRouteImport } from './routes/(menuAdmin)/simpleDishForm'
import { Route as menuClientMenuClientRouteImport } from './routes/(menuClient)/menuClient'
import { Route as menuWaiterMenuWaiterRouteImport } from './routes/(menuWaiter)/menuWaiter'
import { Route as profileChangePasswordRouteImport } from './routes/(profile)/changePassword'
import { Route as profileChangePasswordErrorRouteImport } from './routes/(profile)/changePasswordError'
import { Route as profileChangePasswordSuccessRouteImport } from './routes/(profile)/changePasswordSuccess'
import { Route as profileProfileSettingsRouteImport } from './routes/(profile)/profileSettings'
import { Route as tableAdminAddtableRouteImport } from './routes/(tableAdmin)/Addtable'
import { Route as tableAdminTablesManagmentRouteImport } from './routes/(tableAdmin)/TablesManagment'
import { Route as tableAdminEditTableRouteImport } from './routes/(tableAdmin)/editTable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationAccountSuccessRoute =
  authenticationAccountSuccessRouteImport.update({
    id: '/(authentication)/accountSuccess',
    path: '/accountSuccess',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationAccountVerificationRoute =
  authenticationAccountVerificationRouteImport.update({
    id: '/(authentication)/accountVerification',
    path: '/accountVerification',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationForgotPasswordRoute =
  authenticationForgotPasswordRouteImport.update({
    id: '/(authentication)/forgotPassword',
    path: '/forgotPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationLoginRoute = authenticationLoginRouteImport.update({
  id: '/(authentication)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationPasswordSuccessRoute =
  authenticationPasswordSuccessRouteImport.update({
    id: '/(authentication)/passwordSuccess',
    path: '/passwordSuccess',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationRegisterRoute = authenticationRegisterRouteImport.update({
  id: '/(authentication)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationResetPasswordRoute =
  authenticationResetPasswordRouteImport.update({
    id: '/(authentication)/resetPassword',
    path: '/resetPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationUnexpectedIssueRoute =
  authenticationUnexpectedIssueRouteImport.update({
    id: '/(authentication)/unexpectedIssue',
    path: '/unexpectedIssue',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationUnexpectedIssueVRoute =
  authenticationUnexpectedIssueVRouteImport.update({
    id: '/(authentication)/unexpectedIssueV',
    path: '/unexpectedIssueV',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticationVerificationCodeRoute =
  authenticationVerificationCodeRouteImport.update({
    id: '/(authentication)/verificationCode',
    path: '/verificationCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardCookRoute = dashboardDashboardCookRouteImport.update({
  id: '/(dashboard)/dashboardCook',
  path: '/dashboardCook',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardWaiterRoute =
  dashboardDashboardWaiterRouteImport.update({
    id: '/(dashboard)/dashboardWaiter',
    path: '/dashboardWaiter',
    getParentRoute: () => rootRouteImport,
  } as any)
const menuAdminCustomDishFormRoute = menuAdminCustomDishFormRouteImport.update({
  id: '/(menuAdmin)/customDishForm',
  path: '/customDishForm',
  getParentRoute: () => rootRouteImport,
} as any)
const menuAdminEditMenuRoute = menuAdminEditMenuRouteImport.update({
  id: '/(menuAdmin)/editMenu',
  path: '/editMenu',
  getParentRoute: () => rootRouteImport,
} as any)
const menuAdminMenuManagmentRoute = menuAdminMenuManagmentRouteImport.update({
  id: '/(menuAdmin)/menuManagment',
  path: '/menuManagment',
  getParentRoute: () => rootRouteImport,
} as any)
const menuAdminSimpleDishFormRoute = menuAdminSimpleDishFormRouteImport.update({
  id: '/(menuAdmin)/simpleDishForm',
  path: '/simpleDishForm',
  getParentRoute: () => rootRouteImport,
} as any)
const menuClientMenuClientRoute = menuClientMenuClientRouteImport.update({
  id: '/(menuClient)/menuClient',
  path: '/menuClient',
  getParentRoute: () => rootRouteImport,
} as any)
const menuWaiterMenuWaiterRoute = menuWaiterMenuWaiterRouteImport.update({
  id: '/(menuWaiter)/menuWaiter',
  path: '/menuWaiter',
  getParentRoute: () => rootRouteImport,
} as any)
const profileChangePasswordRoute = profileChangePasswordRouteImport.update({
  id: '/(profile)/changePassword',
  path: '/changePassword',
  getParentRoute: () => rootRouteImport,
} as any)
const profileChangePasswordErrorRoute =
  profileChangePasswordErrorRouteImport.update({
    id: '/(profile)/changePasswordError',
    path: '/changePasswordError',
    getParentRoute: () => rootRouteImport,
  } as any)
const profileChangePasswordSuccessRoute =
  profileChangePasswordSuccessRouteImport.update({
    id: '/(profile)/changePasswordSuccess',
    path: '/changePasswordSuccess',
    getParentRoute: () => rootRouteImport,
  } as any)
const profileProfileSettingsRoute = profileProfileSettingsRouteImport.update({
  id: '/(profile)/profileSettings',
  path: '/profileSettings',
  getParentRoute: () => rootRouteImport,
} as any)
const tableAdminAddtableRoute = tableAdminAddtableRouteImport.update({
  id: '/(tableAdmin)/Addtable',
  path: '/Addtable',
  getParentRoute: () => rootRouteImport,
} as any)
const tableAdminTablesManagmentRoute =
  tableAdminTablesManagmentRouteImport.update({
    id: '/(tableAdmin)/TablesManagment',
    path: '/TablesManagment',
    getParentRoute: () => rootRouteImport,
  } as any)
const tableAdminEditTableRoute = tableAdminEditTableRouteImport.update({
  id: '/(tableAdmin)/editTable',
  path: '/editTable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/accountSuccess': typeof authenticationAccountSuccessRoute
  '/accountVerification': typeof authenticationAccountVerificationRoute
  '/forgotPassword': typeof authenticationForgotPasswordRoute
  '/login': typeof authenticationLoginRoute
  '/passwordSuccess': typeof authenticationPasswordSuccessRoute
  '/register': typeof authenticationRegisterRoute
  '/resetPassword': typeof authenticationResetPasswordRoute
  '/unexpectedIssue': typeof authenticationUnexpectedIssueRoute
  '/unexpectedIssueV': typeof authenticationUnexpectedIssueVRoute
  '/verificationCode': typeof authenticationVerificationCodeRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/dashboardCook': typeof dashboardDashboardCookRoute
  '/dashboardWaiter': typeof dashboardDashboardWaiterRoute
  '/customDishForm': typeof menuAdminCustomDishFormRoute
  '/editMenu': typeof menuAdminEditMenuRoute
  '/menuManagment': typeof menuAdminMenuManagmentRoute
  '/simpleDishForm': typeof menuAdminSimpleDishFormRoute
  '/menuClient': typeof menuClientMenuClientRoute
  '/menuWaiter': typeof menuWaiterMenuWaiterRoute
  '/changePassword': typeof profileChangePasswordRoute
  '/changePasswordError': typeof profileChangePasswordErrorRoute
  '/changePasswordSuccess': typeof profileChangePasswordSuccessRoute
  '/profileSettings': typeof profileProfileSettingsRoute
  '/Addtable': typeof tableAdminAddtableRoute
  '/TablesManagment': typeof tableAdminTablesManagmentRoute
  '/editTable': typeof tableAdminEditTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/accountSuccess': typeof authenticationAccountSuccessRoute
  '/accountVerification': typeof authenticationAccountVerificationRoute
  '/forgotPassword': typeof authenticationForgotPasswordRoute
  '/login': typeof authenticationLoginRoute
  '/passwordSuccess': typeof authenticationPasswordSuccessRoute
  '/register': typeof authenticationRegisterRoute
  '/resetPassword': typeof authenticationResetPasswordRoute
  '/unexpectedIssue': typeof authenticationUnexpectedIssueRoute
  '/unexpectedIssueV': typeof authenticationUnexpectedIssueVRoute
  '/verificationCode': typeof authenticationVerificationCodeRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/dashboardCook': typeof dashboardDashboardCookRoute
  '/dashboardWaiter': typeof dashboardDashboardWaiterRoute
  '/customDishForm': typeof menuAdminCustomDishFormRoute
  '/editMenu': typeof menuAdminEditMenuRoute
  '/menuManagment': typeof menuAdminMenuManagmentRoute
  '/simpleDishForm': typeof menuAdminSimpleDishFormRoute
  '/menuClient': typeof menuClientMenuClientRoute
  '/menuWaiter': typeof menuWaiterMenuWaiterRoute
  '/changePassword': typeof profileChangePasswordRoute
  '/changePasswordError': typeof profileChangePasswordErrorRoute
  '/changePasswordSuccess': typeof profileChangePasswordSuccessRoute
  '/profileSettings': typeof profileProfileSettingsRoute
  '/Addtable': typeof tableAdminAddtableRoute
  '/TablesManagment': typeof tableAdminTablesManagmentRoute
  '/editTable': typeof tableAdminEditTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/(authentication)/accountSuccess': typeof authenticationAccountSuccessRoute
  '/(authentication)/accountVerification': typeof authenticationAccountVerificationRoute
  '/(authentication)/forgotPassword': typeof authenticationForgotPasswordRoute
  '/(authentication)/login': typeof authenticationLoginRoute
  '/(authentication)/passwordSuccess': typeof authenticationPasswordSuccessRoute
  '/(authentication)/register': typeof authenticationRegisterRoute
  '/(authentication)/resetPassword': typeof authenticationResetPasswordRoute
  '/(authentication)/unexpectedIssue': typeof authenticationUnexpectedIssueRoute
  '/(authentication)/unexpectedIssueV': typeof authenticationUnexpectedIssueVRoute
  '/(authentication)/verificationCode': typeof authenticationVerificationCodeRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/(dashboard)/dashboardCook': typeof dashboardDashboardCookRoute
  '/(dashboard)/dashboardWaiter': typeof dashboardDashboardWaiterRoute
  '/(menuAdmin)/customDishForm': typeof menuAdminCustomDishFormRoute
  '/(menuAdmin)/editMenu': typeof menuAdminEditMenuRoute
  '/(menuAdmin)/menuManagment': typeof menuAdminMenuManagmentRoute
  '/(menuAdmin)/simpleDishForm': typeof menuAdminSimpleDishFormRoute
  '/(menuClient)/menuClient': typeof menuClientMenuClientRoute
  '/(menuWaiter)/menuWaiter': typeof menuWaiterMenuWaiterRoute
  '/(profile)/changePassword': typeof profileChangePasswordRoute
  '/(profile)/changePasswordError': typeof profileChangePasswordErrorRoute
  '/(profile)/changePasswordSuccess': typeof profileChangePasswordSuccessRoute
  '/(profile)/profileSettings': typeof profileProfileSettingsRoute
  '/(tableAdmin)/Addtable': typeof tableAdminAddtableRoute
  '/(tableAdmin)/TablesManagment': typeof tableAdminTablesManagmentRoute
  '/(tableAdmin)/editTable': typeof tableAdminEditTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/accountSuccess'
    | '/accountVerification'
    | '/forgotPassword'
    | '/login'
    | '/passwordSuccess'
    | '/register'
    | '/resetPassword'
    | '/unexpectedIssue'
    | '/unexpectedIssueV'
    | '/verificationCode'
    | '/dashboard'
    | '/dashboardCook'
    | '/dashboardWaiter'
    | '/customDishForm'
    | '/editMenu'
    | '/menuManagment'
    | '/simpleDishForm'
    | '/menuClient'
    | '/menuWaiter'
    | '/changePassword'
    | '/changePasswordError'
    | '/changePasswordSuccess'
    | '/profileSettings'
    | '/Addtable'
    | '/TablesManagment'
    | '/editTable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/accountSuccess'
    | '/accountVerification'
    | '/forgotPassword'
    | '/login'
    | '/passwordSuccess'
    | '/register'
    | '/resetPassword'
    | '/unexpectedIssue'
    | '/unexpectedIssueV'
    | '/verificationCode'
    | '/dashboard'
    | '/dashboardCook'
    | '/dashboardWaiter'
    | '/customDishForm'
    | '/editMenu'
    | '/menuManagment'
    | '/simpleDishForm'
    | '/menuClient'
    | '/menuWaiter'
    | '/changePassword'
    | '/changePasswordError'
    | '/changePasswordSuccess'
    | '/profileSettings'
    | '/Addtable'
    | '/TablesManagment'
    | '/editTable'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/(authentication)/accountSuccess'
    | '/(authentication)/accountVerification'
    | '/(authentication)/forgotPassword'
    | '/(authentication)/login'
    | '/(authentication)/passwordSuccess'
    | '/(authentication)/register'
    | '/(authentication)/resetPassword'
    | '/(authentication)/unexpectedIssue'
    | '/(authentication)/unexpectedIssueV'
    | '/(authentication)/verificationCode'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/dashboardCook'
    | '/(dashboard)/dashboardWaiter'
    | '/(menuAdmin)/customDishForm'
    | '/(menuAdmin)/editMenu'
    | '/(menuAdmin)/menuManagment'
    | '/(menuAdmin)/simpleDishForm'
    | '/(menuClient)/menuClient'
    | '/(menuWaiter)/menuWaiter'
    | '/(profile)/changePassword'
    | '/(profile)/changePasswordError'
    | '/(profile)/changePasswordSuccess'
    | '/(profile)/profileSettings'
    | '/(tableAdmin)/Addtable'
    | '/(tableAdmin)/TablesManagment'
    | '/(tableAdmin)/editTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  authenticationAccountSuccessRoute: typeof authenticationAccountSuccessRoute
  authenticationAccountVerificationRoute: typeof authenticationAccountVerificationRoute
  authenticationForgotPasswordRoute: typeof authenticationForgotPasswordRoute
  authenticationLoginRoute: typeof authenticationLoginRoute
  authenticationPasswordSuccessRoute: typeof authenticationPasswordSuccessRoute
  authenticationRegisterRoute: typeof authenticationRegisterRoute
  authenticationResetPasswordRoute: typeof authenticationResetPasswordRoute
  authenticationUnexpectedIssueRoute: typeof authenticationUnexpectedIssueRoute
  authenticationUnexpectedIssueVRoute: typeof authenticationUnexpectedIssueVRoute
  authenticationVerificationCodeRoute: typeof authenticationVerificationCodeRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  dashboardDashboardCookRoute: typeof dashboardDashboardCookRoute
  dashboardDashboardWaiterRoute: typeof dashboardDashboardWaiterRoute
  menuAdminCustomDishFormRoute: typeof menuAdminCustomDishFormRoute
  menuAdminEditMenuRoute: typeof menuAdminEditMenuRoute
  menuAdminMenuManagmentRoute: typeof menuAdminMenuManagmentRoute
  menuAdminSimpleDishFormRoute: typeof menuAdminSimpleDishFormRoute
  menuClientMenuClientRoute: typeof menuClientMenuClientRoute
  menuWaiterMenuWaiterRoute: typeof menuWaiterMenuWaiterRoute
  profileChangePasswordRoute: typeof profileChangePasswordRoute
  profileChangePasswordErrorRoute: typeof profileChangePasswordErrorRoute
  profileChangePasswordSuccessRoute: typeof profileChangePasswordSuccessRoute
  profileProfileSettingsRoute: typeof profileProfileSettingsRoute
  tableAdminAddtableRoute: typeof tableAdminAddtableRoute
  tableAdminTablesManagmentRoute: typeof tableAdminTablesManagmentRoute
  tableAdminEditTableRoute: typeof tableAdminEditTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/accountSuccess': {
      id: '/(authentication)/accountSuccess'
      path: '/accountSuccess'
      fullPath: '/accountSuccess'
      preLoaderRoute: typeof authenticationAccountSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/accountVerification': {
      id: '/(authentication)/accountVerification'
      path: '/accountVerification'
      fullPath: '/accountVerification'
      preLoaderRoute: typeof authenticationAccountVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/forgotPassword': {
      id: '/(authentication)/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof authenticationForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/login': {
      id: '/(authentication)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/passwordSuccess': {
      id: '/(authentication)/passwordSuccess'
      path: '/passwordSuccess'
      fullPath: '/passwordSuccess'
      preLoaderRoute: typeof authenticationPasswordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/register': {
      id: '/(authentication)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authenticationRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/resetPassword': {
      id: '/(authentication)/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof authenticationResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/unexpectedIssue': {
      id: '/(authentication)/unexpectedIssue'
      path: '/unexpectedIssue'
      fullPath: '/unexpectedIssue'
      preLoaderRoute: typeof authenticationUnexpectedIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/unexpectedIssueV': {
      id: '/(authentication)/unexpectedIssueV'
      path: '/unexpectedIssueV'
      fullPath: '/unexpectedIssueV'
      preLoaderRoute: typeof authenticationUnexpectedIssueVRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/verificationCode': {
      id: '/(authentication)/verificationCode'
      path: '/verificationCode'
      fullPath: '/verificationCode'
      preLoaderRoute: typeof authenticationVerificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboardCook': {
      id: '/(dashboard)/dashboardCook'
      path: '/dashboardCook'
      fullPath: '/dashboardCook'
      preLoaderRoute: typeof dashboardDashboardCookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboardWaiter': {
      id: '/(dashboard)/dashboardWaiter'
      path: '/dashboardWaiter'
      fullPath: '/dashboardWaiter'
      preLoaderRoute: typeof dashboardDashboardWaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuAdmin)/customDishForm': {
      id: '/(menuAdmin)/customDishForm'
      path: '/customDishForm'
      fullPath: '/customDishForm'
      preLoaderRoute: typeof menuAdminCustomDishFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuAdmin)/editMenu': {
      id: '/(menuAdmin)/editMenu'
      path: '/editMenu'
      fullPath: '/editMenu'
      preLoaderRoute: typeof menuAdminEditMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuAdmin)/menuManagment': {
      id: '/(menuAdmin)/menuManagment'
      path: '/menuManagment'
      fullPath: '/menuManagment'
      preLoaderRoute: typeof menuAdminMenuManagmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuAdmin)/simpleDishForm': {
      id: '/(menuAdmin)/simpleDishForm'
      path: '/simpleDishForm'
      fullPath: '/simpleDishForm'
      preLoaderRoute: typeof menuAdminSimpleDishFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuClient)/menuClient': {
      id: '/(menuClient)/menuClient'
      path: '/menuClient'
      fullPath: '/menuClient'
      preLoaderRoute: typeof menuClientMenuClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(menuWaiter)/menuWaiter': {
      id: '/(menuWaiter)/menuWaiter'
      path: '/menuWaiter'
      fullPath: '/menuWaiter'
      preLoaderRoute: typeof menuWaiterMenuWaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/changePassword': {
      id: '/(profile)/changePassword'
      path: '/changePassword'
      fullPath: '/changePassword'
      preLoaderRoute: typeof profileChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/changePasswordError': {
      id: '/(profile)/changePasswordError'
      path: '/changePasswordError'
      fullPath: '/changePasswordError'
      preLoaderRoute: typeof profileChangePasswordErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/changePasswordSuccess': {
      id: '/(profile)/changePasswordSuccess'
      path: '/changePasswordSuccess'
      fullPath: '/changePasswordSuccess'
      preLoaderRoute: typeof profileChangePasswordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/profileSettings': {
      id: '/(profile)/profileSettings'
      path: '/profileSettings'
      fullPath: '/profileSettings'
      preLoaderRoute: typeof profileProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tableAdmin)/Addtable': {
      id: '/(tableAdmin)/Addtable'
      path: '/Addtable'
      fullPath: '/Addtable'
      preLoaderRoute: typeof tableAdminAddtableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tableAdmin)/TablesManagment': {
      id: '/(tableAdmin)/TablesManagment'
      path: '/TablesManagment'
      fullPath: '/TablesManagment'
      preLoaderRoute: typeof tableAdminTablesManagmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tableAdmin)/editTable': {
      id: '/(tableAdmin)/editTable'
      path: '/editTable'
      fullPath: '/editTable'
      preLoaderRoute: typeof tableAdminEditTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  authenticationAccountSuccessRoute: authenticationAccountSuccessRoute,
  authenticationAccountVerificationRoute:
    authenticationAccountVerificationRoute,
  authenticationForgotPasswordRoute: authenticationForgotPasswordRoute,
  authenticationLoginRoute: authenticationLoginRoute,
  authenticationPasswordSuccessRoute: authenticationPasswordSuccessRoute,
  authenticationRegisterRoute: authenticationRegisterRoute,
  authenticationResetPasswordRoute: authenticationResetPasswordRoute,
  authenticationUnexpectedIssueRoute: authenticationUnexpectedIssueRoute,
  authenticationUnexpectedIssueVRoute: authenticationUnexpectedIssueVRoute,
  authenticationVerificationCodeRoute: authenticationVerificationCodeRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  dashboardDashboardCookRoute: dashboardDashboardCookRoute,
  dashboardDashboardWaiterRoute: dashboardDashboardWaiterRoute,
  menuAdminCustomDishFormRoute: menuAdminCustomDishFormRoute,
  menuAdminEditMenuRoute: menuAdminEditMenuRoute,
  menuAdminMenuManagmentRoute: menuAdminMenuManagmentRoute,
  menuAdminSimpleDishFormRoute: menuAdminSimpleDishFormRoute,
  menuClientMenuClientRoute: menuClientMenuClientRoute,
  menuWaiterMenuWaiterRoute: menuWaiterMenuWaiterRoute,
  profileChangePasswordRoute: profileChangePasswordRoute,
  profileChangePasswordErrorRoute: profileChangePasswordErrorRoute,
  profileChangePasswordSuccessRoute: profileChangePasswordSuccessRoute,
  profileProfileSettingsRoute: profileProfileSettingsRoute,
  tableAdminAddtableRoute: tableAdminAddtableRoute,
  tableAdminTablesManagmentRoute: tableAdminTablesManagmentRoute,
  tableAdminEditTableRoute: tableAdminEditTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
